### PR TITLE
Replaces minitest with Rspec

### LINKED ISSUE #42: seed file running twice
really low priority. Have no clue why it's doing this. 
on a side note, now seeding cardboard does not use the default `rake db:seed` but rather `rake cardboard:seed`
https://github.com/smashingboxes/cardboard/commit/23f13704883b9a8d2dddc267dd620cb17da812a9

### PR DESCRIPTION
**Pull request by leonelgalan**
## Why?
We, collectively decided (locally with no opposition in #99) that the RSpec ecosystem was a better option. 

## What changed?
* Replaces minitest with Rspec. 
* Fixes #42 (seed file running twice), I did it in this branch, since the solution depends on the dummy App.

### CODE REVIEW

**Comment by iandonovan** [comment]
Nothing leaps out at me as wrong or bad, and the tests passing means things have changed over correctly. +1.

**Comment by joshvc** [comment]
Looks good to me, too. Nice work, @leonelgalan.

**Comment by elfassy** [comment]
@leonelgalan I'm not sure i agree with moving the rake task into the dummy test folder. 
`spec/dummy/lib/tasks/cardboard.rake`

The rake might be used in the tests but it's also used by the main app. I would keep it either where it was or under lib. Thoughts?

**Comment by leonelgalan** [comment]
I don't like it either, but it solves the duplicate run issue. There might be a setup where it still lives under `lib/` but doesn't cause the duplicate, but that will have to be an improvement.  The task is added into the engine rake_tasks, so it's available to the apps using this gem (https://github.com/smashingboxes/cardboard/commit/416dc972304ff28084b46a2dfbc94f9e00c2a5f9#diff-00f7b4514e6dcb073408ccf0314bcc9eR72)

**Comment by elfassy** [comment]
Agreed. Lets put that on the todo list.  No one in a couple of months will  think that we put core functionality in the dummy test app.

**Pull request merged**
