### PR TITLE
fix “add another” wording on page edit

### PR DESCRIPTION
**Pull request by joshvc**
before: "Add another true"
now: "Add another question" (or whatever the part is called)

### CODE REVIEW

**Comment by elfassy** [comment]
I would update the docs for now. 
```
slideshow:
    repeatable: slide
```
seems simple to me. You just don't put that line all together if it's not repeatable. 
Keep in mind reverting this change might break sites using this in production.

**Comment by elfassy** [comment]
the backward compatible compromise would be something like
```ruby
[true, false].include?(part_hash[:repeatable]) ? part_identifier.singularize : part_hash[:repeatable]
```

**Comment by joshvc** [comment]
I don't see how this could break anything in production. The only possibility is if someone, quite by accident and against any logical convention, for `trees` put `repeatable: ficus`.  Now they'll get "Add another tree" instead of "Add another ficus."

**Comment by joeyjoejoejr** [comment]
Yeah, I don't think that backwards compatibility is an issue.  We are about to make a bunch of breaking changes soon anyway.  Ian is going to bump and release everything I've merged today at `0.4.0`.  And then pull in the rails4.2 branch as `0.5.0`.

I think the big question here is whether we think that `repeatable: ficus` is a feature that we should support and document, or if we should do it in another way.  I'm happy to gather opinions and see what other developers think.

**Comment by elfassy** [comment]
`slideshow` would give `Add a new slideshow` instead of `Add a new slide`. This was the use case that lead to this (poorly documented) change.

**Comment by leonelgalan** [comment]
I think we can close this issue. If we need to improve the interface/documentation for this feature, we can submit a new PR and reference this as needed.

**Pull request closed without merging**
